#!/usr/bin/env bash
cd src/rust
cargo update
cd ..
cd ..
R -e "library(utils)
remove.packages('WebGestaltR')
q()"
echo "Old version removed"
R -e "library(devtools)
rextendr::document()
install('.')
q()"
echo "New version installed"
