#!/usr/bin/env bash
# python3 build_hash.py
R -e "library(utils)
remove.packages('WebGestaltR')
q()"
echo "Old version removed"
R -e "library(devtools)
rextendr::document()
install('.')
q()"
echo "New version installed"
