%\VignetteIndexEntry{WebGestaltR}
%\VignetteKeywords{Enrichment analysis, Over-Representation Analysis, GSEA, Pathway, Gene Ontology}
%\VignettePackage{WebGestaltR}


\documentclass[a4paper, oneside, 10pt]{article}

\usepackage[utf8x]{inputenc}
\usepackage[pdftex]{graphicx}
\usepackage{calc}
\usepackage{sectsty}
\usepackage{caption}
\usepackage{underscore}

\renewcommand{\captionfont}{\it\sffamily}
\renewcommand{\captionlabelfont}{\bf\sffamily}
\allsectionsfont{\sffamily}

% page style %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\usepackage[a4paper, left=25mm, right=20mm, top=20mm, bottom=25mm, nohead]{geometry}
\setlength{\parskip}{1.5ex}
\setlength{\parindent}{0cm}
\pagestyle{empty}

\usepackage{hyperref}
\hypersetup{%
unicode=true, 
CJKbookmarks=true, 
bookmarksnumbered=true,
bookmarksopen=true, 
bookmarksopenlevel=1, 
breaklinks=true,
colorlinks=false, 
plainpages=false, 
pdfpagelabels, 
pdfborder=0 0 0 }
\urlstyle{same}

\begin{document}
WebGestaltR is the R version of our well-known web application tool WebGestalt (www.webgestalt.org) that has been visited 57,880 times by 26,233 users from 140 countries and territories in 2016 and has also been cited 371 in 2016. The advantage of this R package is it can be easily integrated to other pipeline or simultaneous analyze multiple gene lists.

WebGestaltR function can perform two popular enrichment analyses: ORA (Over-Representation Analysis) and GSEA (Gene Set Enrichment Analysis). Based on the user uploaded gene list or gene list with scores (for GSEA method),  WebGestaltR function will first map the gene list to the entrez gene ids and then summary the gene list based on the GO (Gene Ontology) Slim. After performing the enrichment analysis, WebGestaltR function also returns an user-friendly HTML report containing the ID mapping table, GO Slim summary result and the enrichment analysis result. If the functional categories have the DAG (directed acyclic graph) structure, the structure of the enriched categories can also be visualized in the report.

\title{Manual of WebGestaltR}
\author{Jing Wang}

\maketitle

\section{Introduction}

\section{Environment}
WebGestaltR requires R version 3.3 or later, which can be downloaded from the website \href{http://www.r-project.org/}{http://www.r-project.org/}.  WebGestaltR package requires the following packages: pkgmaker ($>$=0.22), rjson ($>$=0.2.15), data.table ($>$=1.10.0),  PythonInR ($>$=0.1-3), parallel ($>$3.3.2), doParallel ($>$1.0.10) and foreach ($>$1.4.0), which can be installed as follows.

$>$install.packages("pkgmaker")

$>$install.packages("rjson")

$>$install.packages("data.table")

$>$install.packages("PythonInR")

$>$install.packages("parallel")

$>$install.packages("doParallel")

$>$install.packages("foreach")

\section{WebGestaltR}
After building up the basic environment mentioned above, the users can install the WebGestaltR package and use it to analyze networks.

<<Example>>=

library("WebGestaltR")
#######ORA example#########
#interestGeneFile <- system.file("extdata","interestingGenes.txt",package="WebGestaltR")
#referenceGeneFile <- system.file("extdata","referenceGenes.txt",package="WebGestaltR")
#outputDirectory <- getwd()
#enrichResult <-WebGestaltR(enrichMethod="ORA", organism="hsapiens", enrichDatabase="geneontology_Biological_Process", enrichDatabaseFile=NULL, enrichDatabaseType=NULL, enrichDatabaseDescriptionFile=NULL, interestGeneFile=interestGeneFile, interestGene=NULL, interestGeneType="genesymbol", collapseMethod="mean", referenceGeneFile=referenceGeneFile, referenceGene=NULL, referenceGeneType="genesymbol", referenceSet=NULL, minNum=10, maxNum=500, fdrMethod="BH", sigMethod="fdr", fdrThr=0.01, topThr=10, dNum=20, perNum=1000, lNum=20, is.output=TRUE, outputDirectory=outputDirectory, projectName=NULL, keepGSEAFolder=FALSE,methodType="R",dagColor="continuous",hostName="http://www.webgestalt.org/")

########GSEA example#######
#geneRankFile <- system.file("extdata","GeneRankList.rnk",package="WebGestaltR")
#outputDirectory <- getwd()
#enrichResult <-WebGestaltR(enrichMethod="GSEA", organism="hsapiens", enrichDatabase="pathway_KEGG", enrichDatabaseFile=NULL, enrichDatabaseType=NULL, enrichDatabaseDescriptionFile=NULL, interestGeneFile=geneRankFile, interestGene=NULL, interestGeneType="genesymbol", collapseMethod="mean", referenceGeneFile=NULL, referenceGene=NULL, referenceGeneType=NULL, referenceSet=NULL, minNum=10, maxNum=500, fdrMethod="BH", sigMethod="fdr", fdrThr=0.01, topThr=10, dNum=20, perNum=1000, lNum=20, is.output=TRUE, outputDirectory=outputDirectory, projectName=NULL, keepGSEAFolder=FALSE,methodType="R",hostName="http://www.webgestalt.org/")

@

\subsection{Input}
This section describes the arguments of the WebGestaltR function:

      1. \emph{enrichMethod}: WebGestaltR supports two enrichment analysis methods: ORA (Over-Representation Analysis) and GSEA (Gene Set Enrichment Analysis).
	
      2. \emph{organism}: Currently, WebGestaltR supports 12 organisms. Users can use the function \emph{listOrganism} to check the available organisms. Users can also input \emph{others} to perform the enrichment analysis based on other organisms not supported by WebGestaltR. For the other organisms, users need to upload the enrichment categories, interesting list and reference list (for ORA method). Because WebGestaltR does not perform the ID mapping for the other organisms, the above uploaded data should have the same ID type.

      3. \emph{enrichDatabase}: The functional categories for the enrichment analysis. Users can use the function \emph{listGeneset} to check the available functional databases for the selected organism. Users can also input \emph{others} to upload the functional database not supported by WebGestaltR for the selected organism. 
     
      4. \emph{enrichDatabaseFile}: If users set \emph{organism} as \emph{others} or set \emph{enrichDatabase} as \emph{others}, users need to upload a GMT file as the functional categories for the enrichment analysis. The extension of the file should be \emph{gmt} and the first column of the file is the category ID, the second one is the external link for the category. Genes annotated to the category are from the third column. All columns are separated by tab.
      
      5. \emph{enrichDatabaseType}: If users set \emph{enrichDatabase} as \emph{others}, WebGestaltR will also perform ID mapping for the uploaded GMT file. Thus, users need to set the ID type of the genes in the \emph{enrichDatabaseFile}. If users set \emph{organism} as \emph{others}, users do not need to set this ID type because WebGestaltR will not perform ID mapping for other organisms. The supported ID type of the WebGestaltR for the selected organism can be found by the function \emph{listIDType}.
    
      6. \emph{enrichDatabaseDescriptionFile}: Users can also upload a description file for the uploaded \emph{enrichDatabaseFile}. The extension of the description file should be \emph{des}. The description file contains two columns: the first column is the category ID that should be exactly the same as the category ID in the uploaded \emph{enrichDatabaseFile} and the second column is the description of the category. All columns are separated by tab.
      
      7. \emph{interestGeneFile}: If \emph{enrichMethod} is \emph{ORA}, the extension of the \emph{interestGeneFile} should be \emph{txt} and the file can only contain one column: the interesting gene list. If \emph{enrichMethod} is \emph{GSEA}, the extension of the \emph{interestGeneFile} can be \emph{txt} or \emph{rnk} and the file should contain two columns separated by tab: the gene list and the corresponding scores. 
      
      8. \emph{interestGene}: Users can also use the R object as the input. If \emph{enrichMethod} is \emph{ORA}, \emph{interestGene} should be an R \emph{vector} object containing the interesting gene list. If \emph{enrichMethod} is \emph{GSEA}, \emph{interestGene} should be an R \emph{data.frame} object containing two columns: the gene list and the corresponding scores.
      
      9. \emph{interestGeneType}: The ID type of the interesting gene list. The supported ID type of the WebGestaltR for the selected organism can be found by the function \emph{listIDType}. If the \emph{organism} is \emph{others}, users do not need to set this parameter.
	
      10.  \emph{collapseMethod}: The method to collapse the duplicate ids for the GSEA method. \emph{mean}, \emph{median}, \emph{min} and \emph{max} represent the mean, median, minimum and maximum of scores for the duplicate ids.

      11. \emph{referenceGeneFile}: For ORA method, the users need to upload the reference gene list. The extension of the \emph{referenceGeneFile} should be \emph{txt} and the file can only contain one column: the reference gene list.

      12. \emph{referenceGene}: For ORA method, users can also use the R object as the reference gene list.  \emph{referenceGene} should be an R \emph{vector} object containing the reference gene list.
     
      13. \emph{referenceGeneType}: The ID type of the reference gene list. The supported ID type of the WebGestaltR for the selected organism can be found by the function \emph{listIDType}. If the \emph{organism} is \emph{others}, users do not need to set this parameter.
      
      14. \emph{referenceSet}: Users can directly select the reference set from the existing platform in the WebGestaltR and do not need to upload the reference set. All existing platform supported in the WebGestaltR can be found by the function \emph{listReferenceSet}.If \emph{referenceGeneFile} and \emph{refereneceGene} are \ emph{NULL}, WebGestaltR will use the \emph{referenceSet} as the reference gene set. Otherwise, WebGestaltR will use the user uploaded reference set for the enrichment analysis.

      15. \emph{minNum}: WebGestaltR will exclude the categories with the number of annotated genes less than \emph{minNum} for the enrichment analysis. The default is \emph{10}.

      16. \emph{maxNum}: WebGestaltR will exclude the categories with the number of annotated genes larger than \emph{maxNum} for the enrichment analysis. The default is \emph{500}.
      
      17. \emph{fdrMethod}: For the ORA method, WebGestaltR supports five FDR methods: \emph{holm}, \emph{hochberg}, \emph{hommel}, \emph{bonferroni}, \emph{BH} and \emph{BY}. The default is \emph{BH}.
      
      18. \emph{sigMethod}: Two significant methods are available in the WebGestaltR: \emph{fdr} and \emph{top}. \emph{fdr} means the enriched categories are identified based on the FDR and \emph{top} means all categories are ranked based on FDR and then selected top categories as the enriched categories. The default is \emph{fdr}.
      
      19. \emph{fdrThr}: The significant level for the \emph{fdr} method. The default is \emph{0.05}.
      
      20. \emph{topThr}: The threshold for the \emph{top} method. The default is \emph{10}.
      
      21. \emph{dNum}: The number of enriched categories visualized in the DAG (directed acyclic graph) of the final report if the selected enrichment database contains a DAG structure. The default is \emph{20} and the maximum is \emph{100}. A larger \emph{dNum} will increase the running time.
      
      22. \emph{perNum}: The number of permutations for the GSEA method. The default is \emph{1000}.
      
      23. \emph{lNum}: The number of categories with the output leading edge genes for the GSEA method. The default is \emph{20}. \emph{Note}: GSEA first ranks the categories based on NES (normalized enrichment score) instead of FDR and then outputs the leading edge genes for top \emph{lNum} categories. Because NES does not necessarily decrease with the increase of the FDR, using \emph{sigMethod} defined in WebGestaltR to identify the significant categories may cause some categories with outputted leading edge genes are not included in the final result even if the number of significant categories is larger than \emph{lNum}.
            
      24. \emph{is.output}: If \emph{is.output} is TRUE, WebGestaltR will create a folder named by the \emph{projectName} and save the mapping results, GO slim summary, enrichment results and an user-friendly HTML report in the folder. Otherwise, WebGestaltR will only return an R \emph{data.frame} object containing the enrichment results. If hundreds of gene list need to be analyzed simultaneous, it is better to set \emph{is.output} as FALSE.
      
      25. \emph{outputDirectory}: The output directory for the results.
      
      26. \emph{projectName}: The name of the project. If \emph{projectName} is NULL, WebGestaltR will use time stamp as the project name.
      
      27. \emph{keepGSEAFolder}: If \emph{keepGSEAFolder} is TRUE, WebGestaltR will keep all folders generated from GSEA tool that contain all figures and tables related to the GSEA analysis.
      
      28. \emph{dagColor}: If \emph{dagColor} is binary, the significant terms in the DAG structure will be colored by red for ORA method or red (positive related) and blue (negative related) for GSEA method. If \emph{dagColor} is continous, the significant terms in the DAG structure will be colored by the red gradient for ORA method or red (positive related) and blue (negative related) gradient for GSEA method.based on the corresponding FDR.

      29. \emph{hostName}: The server URL for accessing the data. User can use \emph{listArchiveURL} function to get all archive version URL.
      
\subsection{Output}
The WebGestaltR function not only outputs the user-friendly HTML report containing the ID mapping table, GO Slim summary result and the enrichment analysis result but also outputs an R object containing the enrichment analysis result.

\subsection{NOTE}
Because WebGestaltR will read the data from the server for the ID mapping and GO Slim summary, the running time for the WebGestaltR function will be also based on the internet speed. Generally, it will take around one minute to perform the whole analysis.
Because of the huge number of the Gene ontology categories, running GSEA analysis for these categories may take one to six minutes based on the different size of the uploaded gene rank list. Decreasing the parameter \emph{maxNum} can reduce the running time.

If the user has any problem for the Network Visualization in the HTML report, please follow the instruction in the  http://cytoscapeweb.cytoscape.org/tutorial.

\section{Batch analysis of WebGestaltR}
The WebGestaltR_batch function can perform the batch analysis for multiple gene or ranked gene lists.

\subsection{Input}
	1. \emph{interestGeneFolder}: The folder containing multiple interesting gene files. If \emph{enrichMethod} is \emph{ORA}, the extension of all files should be \emph{txt} and each file can only contain one column: the interesting gene list. If \emph{enrichMethod} is \emph{GSEA}, the extension of each file should be \emph{rnk} and the file should contain two columns separated by tab: the gene list and the corresponding scores.
	
	2. \emph{interestGeneType}: The ID type of the lists in all files. The supported ID type of the WebGestaltR_batch for the selected organism can be found by the function \emph{listIDType}. If the \emph{organism} is \emph{others}, users do not need to set this parameter.
	NOTE: the ID type in all files should be the same.
	
	3. \emph{is_parallel}: If \emph{is_parallel} is TRUE, WebGestaltR_batch will use parallel computing to simultaneously analyze the lists in all files.
	
	4. \emph{nThreads}: The number of cores used for parallel computing.
	
	The description of other parameters can be found in the description of the \emph{WebGestaltR}.

\subsection{Output}
If \emph{is.output} is TRUE, each enriched result will be saved in a folder with the name containing the input file name under the \emph{outputDirectory}. Otherwise, the WebGestaltR_batch function will return a list object containing all results.
	
If there are errors during the calculation, error message can also be found in the returned list object.

\section{Get server URL}
The listArchiveURL function can list the server URL of each version of the data update. Users can select different server URL as the \emph{hostName} to perform the enrichment analysis.

<<Example>>=
#library("WebGestaltR")
#url <- listArchiveURL()
@

\subsection{Output}
The serve URL for all archive versions.

\section{Check the format of the uploaded data}
The formatCheck function can check the format of the gene list or ranked gene list file or object uploaded to the WebGestaltR for the analysis.

<<Example>>=
#library("WebGestaltR")
#geneFile<-system.file("extdata","interestingGenes.txt",package="WebGestaltR")
#interestGene <- formatCheck(dataType="list",inputGeneFile=geneFile,inputGene=NULL)
@

\subsection{Input}
This section describes the arguments of the \emph{formatCheck} function:
      1. \emph{dataType}: Currently, this function supports 2 data type: "list" means the uploaded file or data is a gene list and "rnk" means the uploaded file or data is a ranked gene list with two columns (genes and scores).
       
      2. \emph{inputGeneFile}: The uploaded data file. If the dataType is "list", the file extension should be "txt" and have only one column. If the dataType is "rnk", the file extension should be "rnk" and have two columns (genes and scores).
      
      3. \emph{inputGene}: The uploaded R object. If the dataType is "list", the R object should be a vector. If the dataType is "rnk", the R object should be a data.frame and have two columns (genes and scores).
       
\subsection{Output}
The formatCheck function will return error if the data format is incorrect. Otherwise, it will return the processed data for the analysis.

\section{ID Mapping}
The IDMapping function can map one id type supported by the WebGestaltR to any other id type supported by the WebGestaltR. This function can perform the ID mapping for three types of data: a gene list, a gene list with the scores and a gmt file. 

<<Example>>=
#library("WebGestaltR")
#interestGeneFile <- system.file("extdata","interestingGenes.txt",package="WebGestaltR")
#idmap <- IDMapping(organism="hsapiens", dataType="list", inputGeneFile=interestGeneFile, inputGene=NULL, sourceIdType, targetIdType, collapseMethod="mean", mappingOutput=FALSE, outputFileName="", methodType="R", hostName="http://www.webgestalt.org/")
@

\subsection{Input}
This section describes the arguments of the \emph{IDMapping} function:
      1. \emph{inputGeneFile}: three types of the files are supported for uploading the data: a \emph{txt} file for a gene list, a \emph{rnk} file for a gene list with scores (separated by tab) and a \emph{gmt} file (first column is category id, second one is external link of the cagetory and other columns are the annotated genes. all columns are separated by tab).
       
      2. \emph{dataType}: The IDMapping function can perform the ID mapping for three types of data:  \emph{list} (a gene list), \emph{rnk} (a ranked gene list) and \emph{gmt} (a gmt file).
      
      3. \emph{inputGene}: two types of the R objects are supported for uploading the data: an R \emph{vector} object for a gene list and an R \emph{data.frame} object for a gene list with scores.
      
      4. \emph{sourceIdType}: the ID type of the uploaded data. The supported ID type of the WebGestaltR for the selected organism can be found by the function \emph{listIDType}.
       
      5. \emph{targetIdType}: the target ID type for ID mapping. The supported ID type of the WebGestaltR for the selected organism can be found by the function \emph{listIDType}.
       
      6. \emph{mappingOutput}: if mappingOutput is TRUE, the mapping results will be outputted to a file.
       
      7. \emph{outputFileName}: the output file name. No extension in the file name and the function will add the extension based on the input data type.
  	   
  	  The description of other arguments can be found in the description of the \emph{WebGestaltR} function.  
       
\subsection{Output}
The IDMapping function will output an R data.frame obejct with three types of structure based on the three types of the input data. If the \emph{targetIdType} is one of \emph{entrezgene}, \emph{genesymbol} and \emph{genename}, the output object will contain four columns for a gene list (\emph{userid}, \emph{genesymbol}, \emph{genename} and \emph{entrezgene}), five columns for a gene list with scores (\emph{userid}, \emph{genesymbol}, \emph{genename}, \emph{entrezgene} and \emph{score}) and six columns for a gmt file (\emph{geneset}, \emph{link}, \emph{userid}, \emph{genesymbol}, \emph{genename} and \emph{entrezgene}). If the \emph{targetIdType} is other ID type, the data.frame object will add one more column \emph{targetid}.

\subsection{NOTE}
Because the IDMapping function will read the mapping tables from the server, the running time for the WebGestaltR function will be also based on the internet speed. Generally, it will take around 20 seconds to perform the ID mapping.

\section{GO slim summary}
The \emph{GOSlimSummary} function can summary the gene list based on the biological process, cellular component and molecular function ontologies of the GO Slim data sets. The summary result will be plotted as three bar plots and outputted to the PDF file. 

<<Example>>=
#library("WebGestaltR")
#geneListFile <- system.file("extdata","GOSlimExample.txt",package="WebGestaltR")
#geneList <- read.table(geneListFile, header=FALSE, sep="\t", stringsAsFactors=FALSE)
#geneList <- as.vector(as.matrix(geneList))
#outputFile <- paste(getwd(),"/GOSlimSummary",sep="")
#GOSlimSummary(organism="hsapiens", genelist=geneList, outputFile=outputFile, outputType="pdf", hostName="http://www.webgestalt.org/")
@


\subsection{Input}
This section describes the arguments of the \emph{GOSlimSummary} function:

      1. \emph{genelist}: an R \emph{vector} object containing a gene list. GOSlimSummary only supports NCBI EntrezGene ID for the summary. For other ID types, please first use \emph{IDMapping} function to map to the EntrezGene ID.

      2. \emph{outputFile}: the output file name.
      
      3. \emph{outputType}: The output file extension that can be \emph{pdf}, \emph{png}, or \emph{bmp}.
      
      The description of other arguments can be found in the description of the \emph{WebGestaltR} function. 

	
\subsection{Output}
The \emph{GOSlimSummary} function will output a pdf, png or bmp file with three bar plots.

\subsection{NOTE}
Because the GOSlimSummary function will read the GO Slim data from the server, the running time for the GOSlimSummary function will be also based on the internet speed. Generally, it will take around 20 seconds to perform the summary analysis.

\section{Read GMT file}
The \emph{readGMT} function can read the GMT file and transform to an R matrix object.

\subsection{Input}
This section describes the argument of the \emph{readGMT} function:

      1. \emph{gmtFile}: The GMT file with the extension \emph{gmt}.
	
\subsection{Output}
An R matrix object containing three columns: category ID, external link of the category and the annotated genes.

\section{List organisms}
The \emph{listOrganism} function can list all supported organisms in the WebGestaltR.

<<Example>>=
#library("WebGestaltR")
#organism <- listOrganism(hostName="http://www.webgestalt.org/")
@

\subsection{Input}
This section describes the argument of the \emph{listOrganism} function:
	
	1. \emph{hostName}: The server URL for accessing the data. User can use \emph{listArchiveURL} function to get all archive version URL.

\subsection{Output}
All organisms supported in the WebGestaltR. 

\section{listGeneSet}
The \emph{listGeneSet} function can list all available gene sets for the selected organism in the WebGestaltR.

<<Example>>=
#library("WebGestaltR")
#geneSet <- listGeneSet(organism="hsapiens",hostName="http://www.webgestalt.org/")
@

\subsection{Input}
This section describes the arguments of the \emph{listGeneSet} function:
	
	1. \emph{organism}: Currently, the \emph{listGeneSet} function supports 12 organisms. Users can use the function \emph{listOrganism} to check the available organisms.
	
	2. \emph{hostName}: The server URL for accessing the data. User can use \emph{listArchiveURL} function to get all archive version URL.

\subsection{Output}
All functional categories supported by the WebGestaltR for the selected organism.

\section{listIDType}
The \emph{listIDType} function can list all available ID types for the selected organism in the WebGestaltR.

<<Example>>=
#ibrary("WebGestaltR")
#idType <- listIDType(organism="hsapiens", hostName="http://www.webgestalt.org/")
@

\subsection{Input}
This section describes the arguments of the \emph{listIDType} function:
	
	1. \emph{organism}: Currently, the \emph{listIDType} function supports 12 organisms. Users can use the function \emph{listOrganism} to check the available organisms.
	
	2. \emph{hostName}: The server URL for accessing the data. User can use \emph{listArchiveURL} function to get all archive version URL.

\subsection{Output}
All ID types supported by the WebGestaltR for the selected organism.

\subsection{Output}
All functional categories supported by the WebGestaltR for the selected organism.

\section{listReferenceSet}
The \emph{listReferenceSet} function can list all existing reference sets for the selected organism in the WebGestaltR.

<<Example>>=
#library("WebGestaltR")
#referenceSet <- listReferenceSet(organism="hsapiens", hostName="http://www.webgestalt.org/")
@

\subsection{Input}
This section describes the arguments of the \emph{listReferenceSet} function:
	
	1. \emph{organism}: Currently, the \emph{listIDType} function supports 12 organisms. Users can use the function \emph{listOrganism} to check the available organisms.
	
	2. \emph{hostName}: The server URL for accessing the data. User can use \emph{listArchiveURL} function to get all archive version URL.

\subsection{Output}
All reference sets existing in the WebGestaltR for the selected organism.

\end{document}