[net]
git-fetch-with-cli = true

[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/bzhanglab/webgestalt_rust.git?branch=seed-gsea"]
git = "https://github.com/bzhanglab/webgestalt_rust.git"
branch = "seed-gsea"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
