# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_WebGestaltR_wrappers", use_symbols = TRUE, package_name = "WebGestaltR")

#' @docType package
#' @usage NULL
#' @useDynLib WebGestaltR, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
rust_hello_world <- function() .Call(wrap__rust_hello_world)

#' Fill relation data frame for GSEA input
#'
#' Fill 1 for gene in gene set
#'
#' See https://github.com/extendr/extendr/issues/612 for how to export DataFrame
#'
#' ## Diagram
#' ```shell
#'         Gene Sets
#'       ┌───────────┐  First column named 'gene' containing gene name
#'       │A0100110100│  1 = in set
#' Genes │B0100101000│  0 = not in set
#'       │C1011101001│  Due to limitiations with extendr-api v 0.6.0,
#'       └───────────┘  function returns a list, and the R package will
#'                      add the first 'gene' column
#' ```
#' @param gmt A Data Frame with geneSet and gene columns from the GMT file
#' @param genes A vector of genes
#' @param gene_sets A vector of gene sets
#'
#' @return A Data Frame with the first column of gene and 1 or 0 for other columns of gene sets.
#' @author John Elizarraras
#' @name fill_input_data_frame
#' @keywords internal
#' @export
fill_input_data_frame <- function(gmt, genes, gene_sets) .Call(wrap__fill_input_data_frame, gmt, genes, gene_sets)

#' Run GSEA using rust library
#' @return List of the results of GSEA
#' @name gsea_rust
#' @export
gsea_rust <- function(min_overlap, max_overlap, permutations, sets, parts, analytes, ranks) .Call(wrap__gsea_rust, min_overlap, max_overlap, permutations, sets, parts, analytes, ranks)

#' Run ORA using Rust library
#' @name ora_rust
#' @export
ora_rust <- function(sets, parts, interest, reference) .Call(wrap__ora_rust, sets, parts, interest, reference)


# nolint end
