# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Permutaion in GSEA algorithm
#' 
#' @param inset_scores Scaled score matrix for genes in sets
#' @param outset_scores Normalized score matrix for genes not in sets
#' @param expression_value Vector of gene rank scores
#' 
#' @return A vector of concatenated random minimal,maimum and best running sum scores for each set.
#' @author Yuxing Liao
#' @keywords internal
gseaPermutation <- function(inset_scores, outset_scores, expression_value) {
    .Call('_WebGestaltR_gseaPermutation', PACKAGE = 'WebGestaltR', inset_scores, outset_scores, expression_value)
}

